import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { HumanMessage, SystemMessage, AIMessage, ToolMessage } from "@langchain/core/messages";
import { getSystemPrompt } from "./prompt.js";
import { tools } from "../../tools/index.js";
import { isWebSearchAvailable } from "../../tools/search-web.js";
import type { PRContext } from "../../context/types.js";
import { createCachedChatOpenAI, resetRunningCost, isOverBudget, getRunningCost, getBudget, getRunningInputTokens, getRunningOutputTokens, getRunningCacheReadTokens, getRunningCacheWriteTokens, getToolUsageStats } from "../../helpers/cached-model.js";
import { createPRComment } from "../../context/github.js";
import { processChunk } from "../../helpers/stream-utils.js";
import { getVersion } from "../../helpers/version.js";

// Files that should be excluded from diff context and LOC counting
const LOCK_FILES = ['yarn.lock', 'package-lock.json', 'pnpm-lock.yaml', 'uv.lock', 'poetry.lock', 'Cargo.lock', 'Gemfile.lock', 'composer.lock', 'bun.lockb'];
const BINARY_EXTENSIONS = ['.wasm', '.png', '.jpg', '.jpeg', '.gif', '.ico', '.pdf', '.zip', '.tar', '.gz'];
const ARTIFACT_EXTENSIONS = ['.min.js', '.map', '.svg', '.json'];

/**
 * Check if a file should be excluded from review based on its path
 */
function shouldExcludeFile(fileName: string): boolean {
    const baseName = fileName.split('/').pop() || fileName;
    const lowerFileName = fileName.toLowerCase();

    // Check for lock files
    if (LOCK_FILES.includes(baseName)) return true;

    // Check for binary files
    if (BINARY_EXTENSIONS.some(ext => lowerFileName.endsWith(ext))) return true;

    // Check for artifact files
    if (ARTIFACT_EXTENSIONS.some(ext => lowerFileName.endsWith(ext))) return true;

    // Check for build directories
    if (/\/dist\/|\/build\/|\/out\/|\/node_modules\//.test(fileName)) return true;

    return false;
}

/**
 * Filter out excluded files from a diff string
 */
function filterExcludedFiles(diff: string): string {
    const parts = diff.split(/(?=^diff --git )/m);

    return parts.filter(part => {
        if (!part.trim()) return true;

        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);

        if (match) {
            return !shouldExcludeFile(match[1]);
        }

        return true;
    }).join('');
}

/**
 * Count the number of lines of code changed in a diff
 * Counts lines starting with + or - (excluding diff headers like +++ and ---)
 * Excludes lock files, binaries, and other non-reviewable files
 */
function countDiffLOC(diff: string): number {
    const filteredDiff = filterExcludedFiles(diff);
    const lines = filteredDiff.split('\n');
    let loc = 0;
    for (const line of lines) {
        // Count lines that start with + or - but not +++ or ---
        if ((line.startsWith('+') && !line.startsWith('+++')) ||
            (line.startsWith('-') && !line.startsWith('---'))) {
            loc++;
        }
    }
    return loc;
}

/**
 * Run the PR review agent with the given context
 */
export async function runReview(
    context: PRContext,
    recursionLimit?: number
): Promise<void> {
    // Check if PR exceeds max LOC limit
    const maxLOC = process.env.PR_AGENT_MAX_LOC ? parseInt(process.env.PR_AGENT_MAX_LOC, 10) : null;
    if (maxLOC !== null && !isNaN(maxLOC)) {
        const diffLOC = countDiffLOC(context.diff);
        console.log(`Diff LOC: ${diffLOC}, Max LOC: ${maxLOC}`);

        if (diffLOC > maxLOC) {
            console.log(`PR exceeds max LOC limit (${diffLOC} > ${maxLOC}), refusing to review`);

            const message = `## ⚠️ PR Too Large to Review

This pull request contains **${diffLOC.toLocaleString()} lines of code** changes, which exceeds the configured maximum of **${maxLOC.toLocaleString()} LOC**.

Please consider breaking this PR into smaller, more focused changes for a thorough review.

---
*This message was generated by PR Review Agent*`;

            await createPRComment(context.owner, context.repo, context.prNumber, message);
            return;
        }
    }

    // Reset cost tracking for this run
    resetRunningCost();
    const budget = getBudget();
    console.log(`💵 Budget: $${budget.toFixed(2)}`);

    // Create the model with OpenRouter backend and prompt caching
    const model = createCachedChatOpenAI();

    // Create the React agent
    const agent = createReactAgent({
        llm: model,
        tools,
    });

    // Build the initial context message
    const contextMessage = buildContextMessage(context);

    console.log("::group::🚀 PR Review Agent Starting");
    console.log(`Version: ${getVersion()}`);
    console.log(`Model: ${process.env.MODEL}`);
    console.log(`PR: ${context.owner}/${context.repo}#${context.prNumber}`);
    console.log(`SHA: ${process.env.HEAD_SHA || 'unknown'}`);
    console.log(`Branch: ${context.headBranch} → ${context.baseBranch}`);
    console.log(`Budget: $${budget.toFixed(2)}`);
    console.log(`Recursion Limit: ${recursionLimit}`);
    console.log(`Tools: ${tools.map(t => t.name).join(", ")}`);
    console.log("::endgroup::");

    console.log("\n📝 User Context Message:");
    console.log("─".repeat(60));
    console.log(contextMessage);
    console.log("─".repeat(60));

    // Stream the agent execution
    let stepCount = 0;
    const allMessages: (SystemMessage | HumanMessage | AIMessage | ToolMessage)[] = [
        new SystemMessage(getSystemPrompt(isWebSearchAvailable())),
        new HumanMessage(contextMessage),
    ];

    // Use AbortController to allow proper cancellation of the stream
    const abortController = new AbortController();

    const stream = await agent.stream(
        { messages: allMessages },
        { recursionLimit, signal: abortController.signal }
    );

    let budgetExceeded = false;
    for await (const chunk of stream) {
        stepCount++;
        processChunk(chunk, stepCount, allMessages);

        // Check budget after each step (only flag once)
        if (!budgetExceeded && isOverBudget()) {
            budgetExceeded = true;
            const cost = getRunningCost();
            console.log(`\n⚠️ Budget exceeded ($${cost.toFixed(4)} / $${budget.toFixed(2)}) - will wrap up after current tool calls`);
        }

        // If budget exceeded and we just got tool results, inject wrap-up and break
        // This ensures the LLM sees the budget notice before making more tool calls
        if (budgetExceeded && chunk.tools?.messages) {
            console.log("\n📝 Injecting wrap-up message after tool results...");
            allMessages.push(new HumanMessage("IMPORTANT BUDGET NOTICE: You are past your budget limit. Finish investigating your current checklist item, then submit your review immediately with submit_review. Skip remaining checklist items. Mention in your summary that the review was cut short due to budget constraints."));
            // Abort the stream to stop background processing
            console.log("🛑 Aborting original stream...");
            abortController.abort();
            break;
        }
    }

    // If we broke out due to budget, create a fresh agent for wrap-up
    if (budgetExceeded) {
        console.log("\n📝 Creating fresh model and agent for wrap-up...");

        // Create a completely fresh model instance to avoid any state issues
        const wrapUpModel = createCachedChatOpenAI();

        // Create a new agent instance with the fresh model
        const wrapUpAgent = createReactAgent({
            llm: wrapUpModel,
            tools,
        });

        try {
            const wrapUpStream = await wrapUpAgent.stream(
                { messages: allMessages },
                { recursionLimit: 20 }
            );

            for await (const chunk of wrapUpStream) {
                stepCount++;
                processChunk(chunk, stepCount, allMessages);
            }
            console.log("📝 Wrap-up complete");
        } catch (error) {
            console.error("Wrap-up error:", error);
        }
    }

    const finalCost = getRunningCost();
    const inputTokens = getRunningInputTokens();
    const outputTokens = getRunningOutputTokens();
    const totalTokens = inputTokens + outputTokens;
    const cacheReadTokens = getRunningCacheReadTokens();
    const cacheWriteTokens = getRunningCacheWriteTokens();
    const cacheHitRate = inputTokens > 0 ? (cacheReadTokens / inputTokens * 100) : 0;

    // Get tool usage from global tracking
    const { toolUsage, failedToolUsage, totalCalls: totalToolCalls, totalFailed: totalFailedCalls } = getToolUsageStats();

    console.log(`\n${"=".repeat(60)}`);
    console.log(`Review completed. Total steps: ${stepCount}`);
    console.log(`💰 Final cost: $${finalCost.toFixed(4)} / $${budget.toFixed(2)} budget`);
    console.log(`📊 Tokens: ${inputTokens.toLocaleString()} input, ${outputTokens.toLocaleString()} output, ${totalTokens.toLocaleString()} total`);
    console.log(`💾 Cache: ${cacheHitRate.toFixed(1)}% hit rate (${cacheReadTokens.toLocaleString()} read, ${cacheWriteTokens.toLocaleString()} write)`);
    console.log(`🔧 Tool Usage: ${totalToolCalls} calls${totalFailedCalls > 0 ? ` (${totalFailedCalls} failed)` : ''}`);

    if (totalToolCalls > 0) {
        Object.entries(toolUsage)
            .sort(([, a], [, b]) => b - a)
            .forEach(([name, count]) => {
                const failed = failedToolUsage[name] || 0;
                const failedStr = failed > 0 ? ` (⚠️ ${failed} failed)` : '';
                console.log(`  - ${name}: ${count}${failedStr}`);
            });
    }

    if (totalFailedCalls > 0) {
        console.log(`\n❌ Failed Tools:`);
        Object.entries(failedToolUsage)
            .sort(([, a], [, b]) => b - a)
            .forEach(([name, count]) => {
                console.log(`  - ${name}: ${count} error(s)`);
            });
    }
    console.log("=".repeat(60));
}

/**
 * Extract changed file paths from a diff string, excluding lock/binary/artifact files
 */
function extractChangedFiles(diff: string): string[] {
    const files: string[] = [];
    const parts = diff.split(/(?=^diff --git )/m);

    for (const part of parts) {
        if (!part.trim()) continue;
        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);
        if (match && !shouldExcludeFile(match[1])) {
            files.push(match[1]);
        }
    }

    return files;
}

/**
 * Build the context message for the agent
 */
function buildContextMessage(context: PRContext): string {
    let message = `# Pull Request Review Request

## PR Information
- **Title**: ${context.title}
- **Author**: ${context.author}
- **Branch**: ${context.headBranch} → ${context.baseBranch}

## PR Description
${context.description || "(No description provided)"}
`;

    if (context.commits.length > 0) {
        message += `
## Commits (${context.commits.length})
${context.commits.map((c) => `- \`${c.sha.substring(0, 7)}\` ${c.message.split('\n')[0]} (${c.author})`).join("\n")}
`;
    }

    message += `
## Changed Files Diff
\`\`\`diff
${truncateDiff(context.diff)}
\`\`\`
`;

    if (context.existingComments.length > 0) {
        message += `
## Existing Review Comments
${context.existingComments.map((c) => `- ${c.isResolved ? "✅ " : ""}**${c.author}** on \`${c.path}\`:\n\`\`\`\n${c.body}\n\`\`\``).join("\n")}
`;
    }

    if (context.claudeMd) {
        message += `
## Repository Guidelines (CLAUDE.md)
The repository contains the following guidelines. Treat these as project conventions and respect them when reviewing.
If the guidelines reference files using \`@path/to/file\` syntax (e.g., \`@.claude/docs/api/index.md\`), use read_files to load those files when they would help you understand the code being reviewed. Only read files that are relevant to the changes in this PR.
\`\`\`
${context.claudeMd}
\`\`\`
`;
    }

    if (context.preferences) {
        message += `
## User Preferences
The following preferences have been learned from previous interactions. Please respect these when reviewing:
\`\`\`
${context.preferences}
\`\`\`
`;
    }

    if (context.conversation.length > 0) {
        message += `
## PR Conversation
${context.conversation.map((c) => `- **${c.author}**:\n\`\`\`\n${c.body}\n\`\`\``).join("\n")}
`;
    }

    const changedFiles = extractChangedFiles(context.diff);
    if (changedFiles.length > 0) {
        message += `
## Changed Files Inventory (${changedFiles.length} files)
${changedFiles.map((f, i) => `${i + 1}. ${f}`).join("\n")}
`;
    }

    message += `
## Your Task
Review this pull request. This PR changes ${changedFiles.length} file${changedFiles.length !== 1 ? "s" : ""}. You must examine each one. Begin with Phase 1 (Triage) as described in your instructions.
`;

    return message;
}

/**
 * Truncate diff per file if it's too large
 */
function truncateDiff(diff: string): string {
    const MAX_LINES_PER_FILE = 500;
    const MAX_CHARS_PER_FILE = 40000; // avg 80 characters per line

    // Split by "diff --git" at start of line, keeping the delimiter with each part
    const parts = diff.split(/(?=^diff --git )/m);

    return parts.map(part => {
        if (!part.trim()) return part;

        // Check for binary files or excluded extensions
        // Format: diff --git a/path/to/file.ext b/path/to/file.ext
        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);

        if (match) {
            const fileName = match[1];

            // Use shared exclusion logic
            if (shouldExcludeFile(fileName)) {
                return `${headerLine}\n... (File excluded from diff context)\n`;
            }

            // Special handling for large JS/TS files that might be bundles
            // If it's a JS file and huge, it's likely a bundle we missed
            if (/\.(js|mjs|cjs|ts|tsx)$/.test(fileName) && part.length > MAX_CHARS_PER_FILE) {
                return `${headerLine}\n... (Large file excluded from diff context - likely generated or too big to review inline)\n`;
            }
        }

        // Also check if the diff itself says "Binary files ... differ"
        if (part.includes("Binary files") && part.includes("differ")) {
            return part.split('\n').filter(l => l.startsWith('diff --git') || l.includes('Binary files')).join('\n') + '\n';
        }

        if (part.length > MAX_CHARS_PER_FILE) {
            return part.slice(0, MAX_CHARS_PER_FILE) + "\n... (File diff truncated: exceeds 10k chars)\n";
        }

        const lines = part.split('\n');
        if (lines.length > MAX_LINES_PER_FILE) {
            return lines.slice(0, MAX_LINES_PER_FILE).join('\n') + "\n... (File diff truncated: exceeds 500 lines)\n";
        }

        return part;
    }).join('');
}
