import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { HumanMessage, SystemMessage, AIMessage, ToolMessage } from "@langchain/core/messages";
import { getSystemPrompt } from "./prompt.js";
import { tools } from "../../tools/index.js";
import { isWebSearchAvailable } from "../../tools/search-web.js";
import type { PRContext } from "../../context/types.js";
import { createCachedChatOpenAI } from "../../helpers/cached-model.js";
import { createPRComment } from "../../context/github.js";

/**
 * Count the number of lines of code changed in a diff
 * Counts lines starting with + or - (excluding diff headers like +++ and ---)
 */
function countDiffLOC(diff: string): number {
    const lines = diff.split('\n');
    let loc = 0;
    for (const line of lines) {
        // Count lines that start with + or - but not +++ or ---
        if ((line.startsWith('+') && !line.startsWith('+++')) ||
            (line.startsWith('-') && !line.startsWith('---'))) {
            loc++;
        }
    }
    return loc;
}

/**
 * Run the PR review agent with the given context
 */
export async function runReview(
    context: PRContext,
    recursionLimit: number = 100
): Promise<void> {
    // Check if PR exceeds max LOC limit
    const maxLOC = process.env.PR_AGENT_MAX_LOC ? parseInt(process.env.PR_AGENT_MAX_LOC, 10) : null;
    if (maxLOC !== null && !isNaN(maxLOC)) {
        const diffLOC = countDiffLOC(context.diff);
        console.log(`Diff LOC: ${diffLOC}, Max LOC: ${maxLOC}`);

        if (diffLOC > maxLOC) {
            console.log(`PR exceeds max LOC limit (${diffLOC} > ${maxLOC}), refusing to review`);

            const message = `## ⚠️ PR Too Large to Review

This pull request contains **${diffLOC.toLocaleString()} lines of code** changes, which exceeds the configured maximum of **${maxLOC.toLocaleString()} LOC**.

Please consider breaking this PR into smaller, more focused changes for a thorough review.

---
*This message was generated by PR Review Agent*`;

            await createPRComment(context.owner, context.repo, context.prNumber, message);
            return;
        }
    }

    // Create the model with OpenRouter backend and prompt caching
    const model = createCachedChatOpenAI();

    // Create the React agent
    const agent = createReactAgent({
        llm: model,
        tools,
    });

    // Build the initial context message
    const contextMessage = buildContextMessage(context);

    console.log("=".repeat(60));
    console.log("Starting PR Review Agent");
    console.log("=".repeat(60));
    console.log(`Model: ${process.env.MODEL}`);
    console.log(`Recursion Limit: ${recursionLimit}`);
    console.log(`Tools available: ${tools.map(t => t.name).join(", ")}`);
    console.log("=".repeat(60));

    console.log("\n📝 User Context Message:");
    console.log("─".repeat(60));
    console.log(contextMessage);
    console.log("─".repeat(60));

    // Stream the agent execution to log each step
    let stepCount = 0;
    const stream = await agent.stream(
        {
            messages: [
                new SystemMessage(getSystemPrompt(isWebSearchAvailable())),
                new HumanMessage(contextMessage),
            ],
        },
        {
            recursionLimit,
        }
    );

    for await (const chunk of stream) {
        stepCount++;
        console.log(`\n${"─".repeat(60)}`);
        console.log(`Step ${stepCount}`);
        console.log("─".repeat(60));

        // Log agent messages (LLM responses)
        if (chunk.agent?.messages) {
            for (const msg of chunk.agent.messages) {
                if (msg instanceof AIMessage) {
                    // Log tool calls
                    if (msg.tool_calls && msg.tool_calls.length > 0) {
                        console.log("\n🔧 Tool Calls:");
                        for (const toolCall of msg.tool_calls) {
                            console.log(`  → ${toolCall.name}`);
                            console.log(`    Args: ${JSON.stringify(toolCall.args, null, 2).split('\n').join('\n    ')}`);
                        }
                    }

                    // Log LLM text response
                    if (msg.content && typeof msg.content === 'string' && msg.content.trim()) {
                        console.log("\n💬 Agent Response:");
                        console.log(`  ${msg.content.substring(0, 500)}${msg.content.length > 500 ? '...' : ''}`);
                    }

                    // Log token usage stats
                    const usage = msg.response_metadata?.usage || msg.usage_metadata;
                    if (usage) {
                        console.log("\n📊 Token Usage:");
                        console.log(`  Input: ${usage.input_tokens || usage.prompt_tokens || 'N/A'}`);
                        console.log(`  Output: ${usage.output_tokens || usage.completion_tokens || 'N/A'}`);

                        // Cache stats - check both OpenRouter format and Anthropic format
                        const cacheWrite = usage.prompt_tokens_details?.cache_write_tokens || usage.cache_creation_input_tokens;
                        const cacheRead = usage.prompt_tokens_details?.cached_tokens || usage.cache_read_input_tokens;

                        if (cacheWrite !== undefined && cacheWrite > 0) {
                            console.log(`  Cache Write: ${cacheWrite} tokens`);
                        }
                        if (cacheRead !== undefined && cacheRead > 0) {
                            console.log(`  Cache Read: ${cacheRead} tokens ✨`);
                        }
                    }
                }
            }
        }

        // Log tool results
        if (chunk.tools?.messages) {
            for (const msg of chunk.tools.messages) {
                if (msg instanceof ToolMessage) {
                    const content = typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content);
                    console.log(`\n📤 Tool Result (${msg.name}):`);
                    console.log(`  ${content.substring(0, 300)}${content.length > 300 ? '...' : ''}`);
                }
            }
        }
    }

    console.log(`\n${"=".repeat(60)}`);
    console.log(`Review completed. Total steps: ${stepCount}`);
    console.log("=".repeat(60));
}

/**
 * Build the context message for the agent
 */
function buildContextMessage(context: PRContext): string {
    let message = `# Pull Request Review Request

## PR Information
- **Title**: ${context.title}
- **Author**: ${context.author}
- **Branch**: ${context.headBranch} → ${context.baseBranch}

## PR Description
${context.description || "(No description provided)"}

## Changed Files Diff
\`\`\`diff
${truncateDiff(context.diff)}
\`\`\`
`;

    if (context.existingComments.length > 0) {
        message += `
## Existing Review Comments
${context.existingComments.map((c) => `- **${c.author}** on \`${c.path}\`: ${c.body}`).join("\n")}
`;
    }

    if (context.conversation.length > 0) {
        message += `
## PR Conversation
${context.conversation.map((c) => `- **${c.author}**: ${c.body}`).join("\n")}
`;
    }

    if (context.preferences) {
        message += `
## User Preferences
The following preferences have been learned from previous interactions. Please respect these when reviewing:
\`\`\`
${context.preferences}
\`\`\`
`;
    }

    message += `
## Your Task
Please review this pull request thoroughly. Use the tools available to:
1. Use list_directory to explore the project structure if needed
2. Read any files you need more context on
3. Use grep to search for patterns across the codebase
4. Leave inline comments on specific lines where you find issues
5. Submit your final review with a summary when done

Begin your review now.
`;

    return message;
}

/**
 * Truncate diff per file if it's too large
 */
function truncateDiff(diff: string): string {
    const MAX_LINES_PER_FILE = 500;
    const MAX_CHARS_PER_FILE = 10000;

    // Split by "diff --git" at start of line, keeping the delimiter with each part
    const parts = diff.split(/(?=^diff --git )/m);

    return parts.map(part => {
        if (!part.trim()) return part;

        if (part.length > MAX_CHARS_PER_FILE) {
            return part.slice(0, MAX_CHARS_PER_FILE) + "\n... (File diff truncated: exceeds 10k chars)\n";
        }

        const lines = part.split('\n');
        if (lines.length > MAX_LINES_PER_FILE) {
            return lines.slice(0, MAX_LINES_PER_FILE).join('\n') + "\n... (File diff truncated: exceeds 500 lines)\n";
        }

        return part;
    }).join('');
}
