import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { HumanMessage, SystemMessage, AIMessage, ToolMessage } from "@langchain/core/messages";
import { getSystemPrompt, getPhase1Prompt, getPhase3Prompt } from "./prompt.js";
import { tools, getPhase1Tools, getPhase3Tools } from "../../tools/index.js";
import { isWebSearchAvailable } from "../../tools/search-web.js";
import type { PRContext, ReviewComment } from "../../context/types.js";
import { createCachedChatOpenAI, resetRunningCost, isOverBudget, getRunningCost, getBudget, getRunningInputTokens, getRunningOutputTokens, getRunningCacheReadTokens, getRunningCacheWriteTokens, getToolUsageStats } from "../../helpers/cached-model.js";
import { createPRComment } from "../../context/github.js";
import { processChunk } from "../../helpers/stream-utils.js";
import { getVersion } from "../../helpers/version.js";
import { runSubAgentsInParallel, formatFindings, type ChecklistItem, type SubAgentFinding } from "./sub-agent.js";

// Files that should be excluded from diff context and LOC counting
const LOCK_FILES = ['yarn.lock', 'package-lock.json', 'pnpm-lock.yaml', 'uv.lock', 'poetry.lock', 'Cargo.lock', 'Gemfile.lock', 'composer.lock', 'bun.lockb'];
const BINARY_EXTENSIONS = ['.wasm', '.png', '.jpg', '.jpeg', '.gif', '.ico', '.pdf', '.zip', '.tar', '.gz'];
const ARTIFACT_EXTENSIONS = ['.min.js', '.map', '.svg', '.json'];

/**
 * Check if a file should be excluded from review based on its path
 */
function shouldExcludeFile(fileName: string): boolean {
    const baseName = fileName.split('/').pop() || fileName;
    const lowerFileName = fileName.toLowerCase();

    // Check for lock files
    if (LOCK_FILES.includes(baseName)) return true;

    // Check for binary files
    if (BINARY_EXTENSIONS.some(ext => lowerFileName.endsWith(ext))) return true;

    // Check for artifact files
    if (ARTIFACT_EXTENSIONS.some(ext => lowerFileName.endsWith(ext))) return true;

    // Check for build directories
    if (/\/dist\/|\/build\/|\/out\/|\/node_modules\//.test(fileName)) return true;

    return false;
}

/**
 * Filter out excluded files from a diff string
 */
function filterExcludedFiles(diff: string): string {
    const parts = diff.split(/(?=^diff --git )/m);

    return parts.filter(part => {
        if (!part.trim()) return true;

        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);

        if (match) {
            return !shouldExcludeFile(match[1]);
        }

        return true;
    }).join('');
}

/**
 * Count the number of lines of code changed in a diff
 * Counts lines starting with + or - (excluding diff headers like +++ and ---)
 * Excludes lock files, binaries, and other non-reviewable files
 */
function countDiffLOC(diff: string): number {
    const filteredDiff = filterExcludedFiles(diff);
    const lines = filteredDiff.split('\n');
    let loc = 0;
    for (const line of lines) {
        // Count lines that start with + or - but not +++ or ---
        if ((line.startsWith('+') && !line.startsWith('+++')) ||
            (line.startsWith('-') && !line.startsWith('---'))) {
            loc++;
        }
    }
    return loc;
}

/**
 * Run the PR review agent with the given context
 */
export async function runReview(
    context: PRContext,
    recursionLimit?: number
): Promise<void> {
    // Check if PR exceeds max LOC limit
    const maxLOC = process.env.PR_AGENT_MAX_LOC ? parseInt(process.env.PR_AGENT_MAX_LOC, 10) : null;
    if (maxLOC !== null && !isNaN(maxLOC)) {
        const diffLOC = countDiffLOC(context.diff);
        console.log(`Diff LOC: ${diffLOC}, Max LOC: ${maxLOC}`);

        if (diffLOC > maxLOC) {
            console.log(`PR exceeds max LOC limit (${diffLOC} > ${maxLOC}), refusing to review`);

            const message = `## ⚠️ PR Too Large to Review

This pull request contains **${diffLOC.toLocaleString()} lines of code** changes, which exceeds the configured maximum of **${maxLOC.toLocaleString()} LOC**.

Please consider breaking this PR into smaller, more focused changes for a thorough review.

---
*This message was generated by PR Review Agent*`;

            await createPRComment(context.owner, context.repo, context.prNumber, message);
            return;
        }
    }

    // Reset cost tracking for this run
    resetRunningCost();
    const budget = getBudget();
    const webSearchAvail = isWebSearchAvailable();

    // Build context messages
    const contextMessage = buildContextMessage(context);
    const subAgentContext = buildSubAgentContextMessage(context);

    console.log("::group::🚀 PR Review Agent Starting");
    console.log(`Version: ${getVersion()}`);
    console.log(`Model: ${process.env.MODEL}`);
    console.log(`PR: ${context.owner}/${context.repo}#${context.prNumber}`);
    console.log(`SHA: ${process.env.HEAD_SHA || 'unknown'}`);
    console.log(`Branch: ${context.headBranch} → ${context.baseBranch}`);
    console.log(`Budget: $${budget.toFixed(2)}`);
    console.log(`Recursion Limit: ${recursionLimit}`);
    console.log("::endgroup::");

    console.log("\n📝 User Context Message:");
    console.log("─".repeat(60));
    console.log(contextMessage);
    console.log("─".repeat(60));

    let stepCount = 0;

    // ── Stage A: Phase 1 (Triage) ──────────────────────────────────
    console.log("\n📋 Phase 1: Triage");

    const phase1Tools = getPhase1Tools();
    const phase1Model = createCachedChatOpenAI();
    const phase1Agent = createReactAgent({ llm: phase1Model, tools: phase1Tools });

    const phase1Messages: (SystemMessage | HumanMessage | AIMessage | ToolMessage)[] = [
        new SystemMessage(getPhase1Prompt(webSearchAvail)),
        new HumanMessage(contextMessage),
    ];

    const phase1Abort = new AbortController();
    let phase1BudgetExceeded = false;

    const phase1Stream = await phase1Agent.stream(
        { messages: phase1Messages },
        { recursionLimit, signal: phase1Abort.signal }
    );

    for await (const chunk of phase1Stream) {
        stepCount++;
        processChunk(chunk, stepCount, phase1Messages);

        if (!phase1BudgetExceeded && isOverBudget()) {
            phase1BudgetExceeded = true;
            console.log(`\n⚠️ Budget exceeded during Phase 1 — will submit empty checklist`);
            phase1Abort.abort();
            break;
        }
    }

    // Extract checklist from submit_checklist ToolMessage
    const checklist = extractChecklist(phase1Messages);
    console.log(`\n📋 Checklist: ${checklist.length} item(s)`);

    // ── Fallback: small checklist → single-agent flow ──────────────
    if (checklist.length <= 2) {
        console.log(checklist.length === 0
            ? "\n✅ No issues found in triage — running single-agent for final review"
            : "\n📋 Small checklist (≤2 items) — falling back to single-agent flow");

        await runSingleAgentFlow(contextMessage, webSearchAvail, recursionLimit, stepCount);
        return;
    }

    // ── Stage B: Phase 2 (Parallel Investigation) ──────────────────
    let findings: (SubAgentFinding | null)[];

    if (!isOverBudget()) {
        console.log(`\n🔍 Phase 2: Spawning ${checklist.length} sub-agents for parallel investigation`);

        findings = await runSubAgentsInParallel(
            checklist,
            subAgentContext,
            context.diff,
        );
    } else {
        console.log("\n⚠️ Budget exceeded after Phase 1 — skipping investigation, submitting with triage results only");
        findings = checklist.map(() => null);
    }

    // ── Stage C: Phase 3 (Submit) ──────────────────────────────
    console.log("\n📝 Phase 3: Reviewing findings and submitting");

    const findingsSummary = formatFindings(checklist, findings);

    const phase3Tools = getPhase3Tools();
    const phase3Model = createCachedChatOpenAI();
    const phase3Agent = createReactAgent({ llm: phase3Model, tools: phase3Tools });

    const phase3Messages: (SystemMessage | HumanMessage | AIMessage | ToolMessage)[] = [
        new SystemMessage(getPhase3Prompt(webSearchAvail)),
        new HumanMessage(contextMessage),
        new HumanMessage(findingsSummary),
    ];

    const phase3Abort = new AbortController();
    let phase3BudgetExceeded = false;

    const phase3Stream = await phase3Agent.stream(
        { messages: phase3Messages },
        { recursionLimit, signal: phase3Abort.signal }
    );

    for await (const chunk of phase3Stream) {
        stepCount++;
        processChunk(chunk, stepCount, phase3Messages);

        if (!phase3BudgetExceeded && isOverBudget()) {
            phase3BudgetExceeded = true;
            const cost = getRunningCost();
            console.log(`\n⚠️ Budget exceeded ($${cost.toFixed(4)} / $${budget.toFixed(2)}) — will wrap up`);
        }

        if (phase3BudgetExceeded && chunk.tools?.messages) {
            phase3Messages.push(new HumanMessage("IMPORTANT BUDGET NOTICE: You are past your budget limit. Submit your review immediately with submit_review. Use the findings you already have. Mention in your summary that the review was cut short due to budget constraints."));
            phase3Abort.abort();
            break;
        }
    }

    // Budget wrap-up for Phase 3
    if (phase3BudgetExceeded) {
        console.log("\n📝 Creating fresh agent for wrap-up...");
        const wrapUpModel = createCachedChatOpenAI();
        const wrapUpAgent = createReactAgent({ llm: wrapUpModel, tools: phase3Tools });

        try {
            const wrapUpStream = await wrapUpAgent.stream(
                { messages: phase3Messages },
                { recursionLimit: 20 }
            );
            for await (const chunk of wrapUpStream) {
                stepCount++;
                processChunk(chunk, stepCount, phase3Messages);
            }
            console.log("📝 Wrap-up complete");
        } catch (error) {
            console.error("Wrap-up error:", error);
        }
    }

    logFinalStats(stepCount, budget);
}

/**
 * Extract checklist items from the Phase 1 agent's submit_checklist tool call.
 */
function extractChecklist(messages: any[]): ChecklistItem[] {
    for (const msg of messages) {
        if (msg instanceof ToolMessage && msg.name === 'submit_checklist') {
            try {
                const content = typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content);
                return JSON.parse(content) as ChecklistItem[];
            } catch {
                console.error("Failed to parse submit_checklist output");
            }
        }
    }
    return [];
}

/**
 * Fallback: run the original single-agent flow for small PRs (≤2 checklist items).
 */
async function runSingleAgentFlow(
    contextMessage: string,
    webSearchAvail: boolean,
    recursionLimit: number | undefined,
    initialStepCount: number,
): Promise<void> {
    const budget = getBudget();
    const model = createCachedChatOpenAI();
    const agent = createReactAgent({ llm: model, tools });

    let stepCount = initialStepCount;
    const allMessages: (SystemMessage | HumanMessage | AIMessage | ToolMessage)[] = [
        new SystemMessage(getSystemPrompt(webSearchAvail)),
        new HumanMessage(contextMessage),
    ];

    const abortController = new AbortController();
    const stream = await agent.stream(
        { messages: allMessages },
        { recursionLimit, signal: abortController.signal }
    );

    let budgetExceeded = false;
    for await (const chunk of stream) {
        stepCount++;
        processChunk(chunk, stepCount, allMessages);

        if (!budgetExceeded && isOverBudget()) {
            budgetExceeded = true;
            const cost = getRunningCost();
            console.log(`\n⚠️ Budget exceeded ($${cost.toFixed(4)} / $${budget.toFixed(2)}) - will wrap up after current tool calls`);
        }

        if (budgetExceeded && chunk.tools?.messages) {
            allMessages.push(new HumanMessage("IMPORTANT BUDGET NOTICE: You are past your budget limit. Finish investigating your current checklist item, then submit your review immediately with submit_review. Skip remaining checklist items. Mention in your summary that the review was cut short due to budget constraints."));
            abortController.abort();
            break;
        }
    }

    if (budgetExceeded) {
        const wrapUpModel = createCachedChatOpenAI();
        const wrapUpAgent = createReactAgent({ llm: wrapUpModel, tools });

        try {
            const wrapUpStream = await wrapUpAgent.stream(
                { messages: allMessages },
                { recursionLimit: 20 }
            );
            for await (const chunk of wrapUpStream) {
                stepCount++;
                processChunk(chunk, stepCount, allMessages);
            }
        } catch (error) {
            console.error("Wrap-up error:", error);
        }
    }

    logFinalStats(stepCount, budget);
}

/**
 * Log final cost, token, and tool usage statistics.
 */
function logFinalStats(stepCount: number, budget: number): void {
    const finalCost = getRunningCost();
    const inputTokens = getRunningInputTokens();
    const outputTokens = getRunningOutputTokens();
    const totalTokens = inputTokens + outputTokens;
    const cacheReadTokens = getRunningCacheReadTokens();
    const cacheWriteTokens = getRunningCacheWriteTokens();
    const cacheHitRate = inputTokens > 0 ? (cacheReadTokens / inputTokens * 100) : 0;

    const { toolUsage, failedToolUsage, totalCalls: totalToolCalls, totalFailed: totalFailedCalls } = getToolUsageStats();

    console.log(`\n${"=".repeat(60)}`);
    console.log(`Review completed. Total steps: ${stepCount}`);
    console.log(`💰 Final cost: $${finalCost.toFixed(4)} / $${budget.toFixed(2)} budget`);
    console.log(`📊 Tokens: ${inputTokens.toLocaleString()} input, ${outputTokens.toLocaleString()} output, ${totalTokens.toLocaleString()} total`);
    console.log(`💾 Cache: ${cacheHitRate.toFixed(1)}% hit rate (${cacheReadTokens.toLocaleString()} read, ${cacheWriteTokens.toLocaleString()} write)`);
    console.log(`🔧 Tool Usage: ${totalToolCalls} calls${totalFailedCalls > 0 ? ` (${totalFailedCalls} failed)` : ''}`);

    if (totalToolCalls > 0) {
        Object.entries(toolUsage)
            .sort(([, a], [, b]) => b - a)
            .forEach(([name, count]) => {
                const failed = failedToolUsage[name] || 0;
                const failedStr = failed > 0 ? ` (⚠️ ${failed} failed)` : '';
                console.log(`  - ${name}: ${count}${failedStr}`);
            });
    }

    if (totalFailedCalls > 0) {
        console.log(`\n❌ Failed Tools:`);
        Object.entries(failedToolUsage)
            .sort(([, a], [, b]) => b - a)
            .forEach(([name, count]) => {
                console.log(`  - ${name}: ${count} error(s)`);
            });
    }
    console.log("=".repeat(60));
}

/**
 * Extract changed file paths from a diff string, excluding lock/binary/artifact files
 */
function extractChangedFiles(diff: string): string[] {
    const files: string[] = [];
    const parts = diff.split(/(?=^diff --git )/m);

    for (const part of parts) {
        if (!part.trim()) continue;
        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);
        if (match && !shouldExcludeFile(match[1])) {
            files.push(match[1]);
        }
    }

    return files;
}

/**
 * Format an ISO timestamp as a short datetime string
 */
function formatTimestamp(iso: string): string {
    if (!iso) return "";
    const d = new Date(iso);
    if (isNaN(d.getTime())) return iso;
    return d.toISOString().replace("T", " ").replace(/\.\d+Z$/, "");
}

function parseTimestamp(iso: string): number {
    if (!iso) return 0;
    const t = new Date(iso).getTime();
    return isNaN(t) ? 0 : t;
}

/**
 * Group review comments into threads. Thread roots are comments without inReplyToId.
 * Returns an array of threads, each with a root comment and its replies sorted chronologically.
 */
function buildReviewThreads(comments: ReviewComment[]): { root: ReviewComment; replies: ReviewComment[] }[] {
    const rootMap = new Map<number, { root: ReviewComment; replies: ReviewComment[] }>();

    // First pass: identify thread roots
    for (const c of comments) {
        if (!c.inReplyToId) {
            rootMap.set(c.id, { root: c, replies: [] });
        }
    }

    // Second pass: attach replies to their roots
    for (const c of comments) {
        if (c.inReplyToId) {
            const thread = rootMap.get(c.inReplyToId);
            if (thread) {
                thread.replies.push(c);
            } else {
                // Reply to a reply or orphaned — treat as standalone root
                rootMap.set(c.id, { root: c, replies: [] });
            }
        }
    }

    // Sort replies within each thread chronologically
    for (const thread of rootMap.values()) {
        thread.replies.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
    }

    return Array.from(rootMap.values());
}

/**
 * Render a review comment thread as a timeline entry
 */
function indent(text: string, prefix: string): string {
    return text.split('\n').join(`\n${prefix}`);
}

function renderThread(thread: { root: ReviewComment; replies: ReviewComment[] }): string {
    const { root, replies } = thread;
    const location = root.line ? `\`${root.path}:${root.line}\`` : `\`${root.path}\``;
    const resolved = root.isResolved ? " ✅ resolved" : "";
    let text = `💬 Review thread on ${location}${resolved}\n`;
    text += `  **${root.author}**: ${indent(root.body, '  ')}`;
    for (const reply of replies) {
        text += `\n    ↳ **${reply.author}**: ${indent(reply.body, '      ')}`;
    }
    return text;
}

/**
 * Build a unified chronological timeline of all PR activity:
 * commits, conversation comments, review comment threads, and review summaries.
 */
function buildActivityTimeline(context: PRContext): string {
    type TimelineEvent = { timestamp: string; render: string };
    const events: TimelineEvent[] = [];

    // Commits
    for (const c of context.commits) {
        events.push({
            timestamp: c.date,
            render: `🔨 **${c.author}** pushed \`${c.sha.substring(0, 7)}\` — ${c.message.split('\n')[0]}`,
        });
    }

    // Conversation (issue comments)
    for (const c of context.conversation) {
        events.push({
            timestamp: c.createdAt,
            render: `💬 **${c.author}**: ${c.body}`,
        });
    }

    // Review comment threads (grouped)
    const threads = buildReviewThreads(context.existingComments);
    for (const thread of threads) {
        events.push({
            timestamp: thread.root.createdAt,
            render: renderThread(thread),
        });
    }

    // Review summaries
    for (const r of context.reviewSummaries) {
        events.push({
            timestamp: r.submittedAt,
            render: `📋 **${r.author}** submitted review (${r.state}):\n  ${indent(r.body, '  ')}`,
        });
    }

    if (events.length === 0) return "";

    // Sort chronologically
    events.sort((a, b) => parseTimestamp(a.timestamp) - parseTimestamp(b.timestamp));

    return events.map((e) => `[${formatTimestamp(e.timestamp)}] ${e.render}`).join("\n\n");
}

/**
 * Build the context message for the agent
 */
function buildContextMessage(context: PRContext): string {
    let message = `# Pull Request Review Request

## PR Information
- **Title**: ${context.title}
- **Author**: ${context.author}
- **Branch**: ${context.headBranch} → ${context.baseBranch}
- **Your Identity**: You are \`${context.botLogin}\`. Comments and reviews by this user in the timeline below are from your previous runs.

## PR Description
${context.description || "(No description provided)"}
`;

    message += `
## Changed Files Diff
\`\`\`diff
${truncateDiff(context.diff)}
\`\`\`
`;

    // Build unified PR activity timeline
    const timeline = buildActivityTimeline(context);
    if (timeline) {
        message += `
## PR Activity Timeline
${timeline}
`;
    }

    if (context.claudeMd) {
        message += `
## Repository Guidelines (CLAUDE.md)
The repository contains the following guidelines. Treat these as project conventions and respect them when reviewing.
If the guidelines reference files using \`@path/to/file\` syntax (e.g., \`@.claude/docs/api/index.md\`), use read_files to load those files when they would help you understand the code being reviewed. Only read files that are relevant to the changes in this PR.
\`\`\`
${context.claudeMd}
\`\`\`
`;
    }

    if (context.preferences) {
        message += `
## User Preferences
The following preferences have been learned from previous interactions. Please respect these when reviewing:
\`\`\`
${context.preferences}
\`\`\`
`;
    }

    const changedFiles = extractChangedFiles(context.diff);
    if (changedFiles.length > 0) {
        message += `
## Changed Files Inventory (${changedFiles.length} files)
${changedFiles.map((f, i) => `${i + 1}. ${f}`).join("\n")}
`;
    }

    message += `
## Your Task
Review this pull request. This PR changes ${changedFiles.length} file${changedFiles.length !== 1 ? "s" : ""}. You must examine each one. Begin with the review process as described in your instructions (starting with Phase 0 if you have previous reviews, otherwise Phase 1).
`;

    return message;
}

/**
 * Build a lightweight context message for sub-agents (no diff, no task instructions).
 * Sub-agents receive their filtered diff separately.
 */
function buildSubAgentContextMessage(context: PRContext): string {
    let message = `# Pull Request Context

## PR Information
- **Title**: ${context.title}
- **Author**: ${context.author}
- **Branch**: ${context.headBranch} → ${context.baseBranch}
`;

    if (context.description) {
        message += `
## PR Description
${context.description}
`;
    }

    if (context.claudeMd) {
        message += `
## Repository Guidelines (CLAUDE.md)
\`\`\`
${context.claudeMd}
\`\`\`
`;
    }

    const changedFiles = extractChangedFiles(context.diff);
    if (changedFiles.length > 0) {
        message += `
## Changed Files Inventory (${changedFiles.length} files)
${changedFiles.map((f, i) => `${i + 1}. ${f}`).join("\n")}
`;
    }

    return message;
}

/**
 * Truncate diff per file if it's too large
 */
function truncateDiff(diff: string): string {
    const MAX_LINES_PER_FILE = 500;
    const MAX_CHARS_PER_FILE = 40000; // avg 80 characters per line

    // Split by "diff --git" at start of line, keeping the delimiter with each part
    const parts = diff.split(/(?=^diff --git )/m);

    return parts.map(part => {
        if (!part.trim()) return part;

        // Check for binary files or excluded extensions
        // Format: diff --git a/path/to/file.ext b/path/to/file.ext
        const headerLine = part.split('\n')[0];
        const match = headerLine.match(/diff --git a\/(.*?) b\//);

        if (match) {
            const fileName = match[1];

            // Use shared exclusion logic
            if (shouldExcludeFile(fileName)) {
                return `${headerLine}\n... (File excluded from diff context)\n`;
            }

            // Special handling for large JS/TS files that might be bundles
            // If it's a JS file and huge, it's likely a bundle we missed
            if (/\.(js|mjs|cjs|ts|tsx)$/.test(fileName) && part.length > MAX_CHARS_PER_FILE) {
                return `${headerLine}\n... (Large file excluded from diff context - likely generated or too big to review inline)\n`;
            }
        }

        // Also check if the diff itself says "Binary files ... differ"
        if (part.includes("Binary files") && part.includes("differ")) {
            return part.split('\n').filter(l => l.startsWith('diff --git') || l.includes('Binary files')).join('\n') + '\n';
        }

        if (part.length > MAX_CHARS_PER_FILE) {
            return part.slice(0, MAX_CHARS_PER_FILE) + "\n... (File diff truncated: exceeds 10k chars)\n";
        }

        const lines = part.split('\n');
        if (lines.length > MAX_LINES_PER_FILE) {
            return lines.slice(0, MAX_LINES_PER_FILE).join('\n') + "\n... (File diff truncated: exceeds 500 lines)\n";
        }

        return part;
    }).join('');
}
