import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { createPRComment } from "../context/github.js";

/**
 * Tool to submit the final review with a summary
 */
export const submitReviewTool = tool(
    async ({ summary, verdict }) => {
        const owner = process.env.REPO_OWNER!;
        const repo = process.env.REPO_NAME!;
        const prNumber = parseInt(process.env.PR_NUMBER!, 10);

        try {
            // Build the review summary comment
            const verdictEmoji = {
                approve: "✅",
                request_changes: "⚠️",
                comment: "💬",
            }[verdict];

            const verdictText = {
                approve: "Looks good!",
                request_changes: "Changes requested",
                comment: "Review complete",
            }[verdict];

            const body = `## ${verdictEmoji} ${verdictText}

${summary}

---
*This review was generated by PR Review Agent*`;

            await createPRComment(owner, repo, prNumber, body);

            return `Review submitted successfully with verdict: ${verdict}`;
        } catch (error) {
            const message = error instanceof Error ? error.message : "Unknown error";
            return `Error submitting review: ${message}`;
        }
    },
    {
        name: "submit_review",
        description:
            "Submit the final review with a summary comment. Call this after leaving all inline comments to provide an overall assessment of the PR.",
        schema: z.object({
            summary: z
                .string()
                .describe(
                    "A summary of your review findings. Include key issues found, positive aspects, and overall recommendations."
                ),
            verdict: z
                .enum(["approve", "request_changes", "comment"])
                .describe(
                    "Your overall verdict: 'approve' if the code is good, 'request_changes' if there are issues that must be fixed, 'comment' for feedback without blocking."
                ),
        }),
    }
);
